# Generated by Django 4.2.6 on 2023-12-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_description'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='click',
            index_together={('job', 'session_id')},
        ),
        migrations.AlterIndexTogether(
            name='impression',
            index_together={('job', 'session_id')},
        ),
    ]
