# Generated by Django 4.2.6 on 2023-12-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_click_index_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
