# Generated by Django 4.2.6 on 2024-01-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('job_count', 'name'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='job_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
