# Generated by Django 4.2.6 on 2024-01-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_job_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-job_count', '-created_at', '-name'), 'verbose_name_plural': 'Locations'},
        ),
    ]
